### ISSUE TITLE
Clock skew reported but ntpq does not show clock skew

### ISSUE THREAD

**Issue by jchodera** [FoldingAtHome/fah-client-pub#1146]
See detailed report here: https://github.com/cBio/cbio-cluster/issues/302

In short, logs report clock skew but nodes are synced via NTP pool and no skew detected by `ntpq`.  

Could there be other issues that cause clock skew reports?

**Comment by jcoffland** [comment]
This is caused by a detected difference between the WS clock and the client's clock.  It could be that the WS clock is off or that there was a significant delay on the network.  The report above does not indicate which WS was involved so I cannot check the WS's clock.

Either way it's not a big problem.  The client corrects for the difference so that it can compute more accurate WU timeout/deadline times.  The point is that if a client's time is vastly different from the WS it can still fold correctly.

**Comment by jchodera** [comment]
For the record, the WS for project 10495 is `plfah2-5.mskcc.org`.

**Comment by jcoffland** [comment]
Scratch my previous explanation.  The client does have the above described feature but this is something else.

Those messages indicate that the client detected a significant delay in it's processing loop.  This can be caused by:

  1. The machine going to sleep or in to hibernation.
  2. The client process being suspended.
  3. A very slow system.
  4. Long delays due to the client blocking on disk IO.  Possibly caused by a network drive.

If the client is making these complaints there's a good chance one of these things is going on.  When such a delay is detected the client assumes that the core was also not running during this period and subtracts the time from it's tally of the WU runtime for ETA estimation purposes.  The usual case is when a laptop is put to sleep and the client resumes processing.  With out this correction it will have a wildly inaccurate ETA estimate after sleeping.

**Comment by jchodera** [comment]
Thanks for the clarification!  This was a compute cluster, so 1 and 2 are not relevant, but it is very possible that some interfering jobs (not behaving as they should) or significant I/O (which spiked last night) was the cause.  Investigating this now.

Perhaps the message could be generalized to "Clock skew, I/O delays, or other slowdown noted" or similar?

**Comment by jcoffland** [comment]
Done.
