### ISSUE TITLE
Ubuntu 16.04 LTS breaks FAH install -- incompatible python version

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-client-pub#1164]
Installation Warnings/Errors on Ubuntu 16.04

>W: fahcontrol: new-package-should-close-itp-bug
>E: fahcontrol: depends-on-obsolete-package depends: python-support (>= 0.90.0) => use dh_python2 instead
>W: fahcontrol: binary-without-manpage usr/bin/FAHControl

**Comment by jcoffland** [comment]
I believe this was fixed in v7.4.15. Reopen if not.

**Comment by matthewbeckler** [comment]
I was unable to install FAH on Ubuntu 16.04.2 LTS today due the the python-support (>= 0.90.0) dependency in the control .deb file.

Since you mentioned that this was fixed in v7.4.15, but the current website is only offering v7.4.4 for download, perhaps the website needs to be updated to offer v7.4.15? https://folding.stanford.edu/start-folding/

Using the workaround posted here (https://foldingforum.org/viewtopic.php?p=285382#p285382) resolved the issue:
wget http://launchpadlibrarian.net/109052632/python-support_1.0.15_all.deb
sudo dpkg -i python-support_1.0.15_all.deb

**Comment by jcoffland** [comment]
@matthewbeckler, thanks for the info.  v7.4.15 is still in beta testing.  You can find the beta downloads here: http://folding.stanford.edu/beta/

**Comment by Rooks103** [comment]
@jcoffland So I just tried downloading the v7.4.16 beta and got the same issue with the python-support version.  

Running @matthewbeckler posted workaround allowed me to install either the standard 7.4.4 or 7.4.16.
`wget http://launchpadlibrarian.net/109052632/python-support_1.0.15_all.deb
sudo dpkg -i python-support_1.0.15_all.deb`

**Comment by rwthompsonii** [comment]
Checking in to post that I'm on 17.10 and *still* have to use the workaround: `wget http://launchpadlibrarian.net/109052632/python-support_1.0.15_all.deb
sudo dpkg -i python-support_1.0.15_all.deb` in order to get the FAHControl to launch.

**Comment by beala** [comment]
I also have this problem on Ubuntu 16.04 LTS. I've tried installing both `fahcontrol_7.4.4-1_all` and `fahcontrol_7.4.16-1_all`.

I understand there's a workaround, but I'm wary of directly installing packages from launchpad that have been marked as deprecated.
